FROM python:3.10-slim

WORKDIR /app

# Install build tools
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y build-essential && \
    rm -rf /var/lib/apt/lists/*

COPY ../requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "project_root.api.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
